print("Ahoj")
print('Ahoj')
print("""Ahoj
Hugo""")
print("🍦")
print("\N{SOFT ICE CREAM}")
print("\U0001F366")
print("Ahoj\nHugo")
print("C:\\")
print("A\tb")
print("Ahoj\tb")
print("Chci napsat \"")
print('Chci napsat \'')
print("Chci napsat '")